package com.openxt.uploadsshfile.cliapi;

import java.nio.charset.StandardCharsets;
import java.util.HexFormat;

/**
 * CLI 启动器 bat 模板（1.0.8 / D-23，设计文档 §5.1/§9；不随包——由插件 startup activity
 * 首启生成于 {@code <IDEA配置>/plugins/uploadsshfile/uploadsshfile-cli.bat}）。
 *
 * <p>纯 ASCII（R23/AC-21）；两处实值由生成机注入：
 * <ol>
 *   <li><b>java 绝对路径</b>＝{@code System.getProperty("java.home")\bin\java.exe}——
 *       即当前运行本插件的 IDEA 自带 JBR（21+），不假设 PATH/JAVA_HOME、
 *       版本与 class 字节码同源（用户追加裁定 2026-10-01）；</li>
 *   <li><b>配置目录推导</b>＝{@code %~dp0..\\..\\uploadsshfile}（§5.1，R34——本机 idea.properties
 *       重定向场景实证唯一可靠路线），以 {@code --config-dir} 显式传给 Main，Main 不自行猜。</li>
 * </ol>
 *
 * <p>完整性自检（D-23）：期望 MD5＝{@link #content(String)} 运行时计算（模板改则期望值自动跟随，
 * 与磁盘 bat 的字节 MD5 比对——缺失/篡改/滞后三态合一，不合法即原子重生成）。
 * bat 拷贝到别的机器：对方 IDEA 首启时 java.home 不同→期望 MD5 不同→自动重生成本机版，自愈闭环。
 */
public final class BatScriptTemplate {

    public static final String FILE_NAME = "uploadsshfile-cli.bat";
    public static final String MAIN_CLASS = "com.openxt.uploadsshfile.cli.Main";

    private BatScriptTemplate() {
    }

    /**
     * 生成本机 bat 全文。
     * @param javaHome IDEA 进程 java.home（System.getProperty("java.home")，由 plugin 层传入以保持 core 无环境耦合/可单测）
     */
    public static String content(String javaHome) {
        String javaExe = javaHome.endsWith("bin")
                ? javaHome + java.io.File.separator + "java.exe"
                : javaHome + java.io.File.separator + "bin" + java.io.File.separator + "java.exe";
        StringBuilder sb = new StringBuilder();
        sb.append("@echo off\r\n");
        sb.append("rem UploadSSHFile CLI launcher -- generated by plugin startup activity (do not edit;");
        sb.append(" edits will be reverted by integrity check)\r\n");
        sb.append("rem Regenerate baseline: java.home of the IDEA running this plugin; lib = %~dp0lib\r\n");
        sb.append("setlocal\r\n");
        sb.append("set \"JAVA=").append(javaExe).append("\"\r\n");
        sb.append("set \"CFG=%~dp0..\\..\\uploadsshfile\"\r\n");
        sb.append("\"%JAVA%\" -cp \"%~dp0lib\\*\" ").append(MAIN_CLASS).append(" --config-dir \"%CFG%\" %*\r\n");
        sb.append("set \"EC=%ERRORLEVEL%\"\r\n");
        sb.append("if not defined NO_PAUSE pause\r\n");
        sb.append("exit /b %EC%\r\n");
        return sb.toString();
    }

    /** 期望 MD5（模板运行时推导——思想实验 #9 追问裁定；入参＝本机 java.home） */
    public static String expectedMd5(String javaHome) {
        try {
            java.security.MessageDigest md = java.security.MessageDigest.getInstance("MD5");
            byte[] digest = md.digest(content(javaHome).getBytes(StandardCharsets.UTF_8));
            return HexFormat.of().withUpperCase().formatHex(digest);
        } catch (java.security.NoSuchAlgorithmException e) {
            throw new IllegalStateException("MD5 unavailable", e);
        }
    }

    /** 磁盘 bat 字节 MD5（null＝文件不存在） */
    public static String actualMd5(java.nio.file.Path batFile) {
        if (batFile == null || !java.nio.file.Files.exists(batFile)) {
            return null;
        }
        try {
            java.security.MessageDigest md = java.security.MessageDigest.getInstance("MD5");
            byte[] digest = md.digest(java.nio.file.Files.readAllBytes(batFile));
            return HexFormat.of().withUpperCase().formatHex(digest);
        } catch (Exception e) {
            return ""; // 读失败＝不合法，触发重生成
        }
    }
}
